### ISSUE TITLE
Wrong language code for Indonesian translation

### ISSUE THREAD

**Issue by zmni** [TachibanaGeneralLaboratories/download-navi#50]
Actually there are 2 language code for Indonesian language. `id` which is newer and `in` which is older and deprecated ([ref](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)). And Android is [stuck with the old one](https://developer.android.com/reference/java/util/Locale#legacy-language-codes), `in`.

Can you change the code? Or better keep them both for future compatibility.

Thank you.

**Comment by proninyaroslav** [comment]
Fixed https://github.com/TachibanaGeneralLaboratories/download-navi/commit/5cd0142c514288cb46261e26081244aca693e4df. Fastlane and F-Droid seem to be using the correct `id` code, please check it https://github.com/TachibanaGeneralLaboratories/download-navi/tree/master/fastlane/metadata/android/id

**Comment by zmni** [comment]
For the store description? Unfortunately it also need the `in` code.

![Screenshot_20200104-220029](https://user-images.githubusercontent.com/841523/71767523-8fc94980-2f3f-11ea-8957-7b6c24a19136.png)

**Comment by proninyaroslav** [comment]
This is strange. I duplicated the code to `in` 394a213

**Comment by zmni** [comment]
Have you published these changes to the Play Store? I'm still seeing v1.1.1.
________________________________

**Comment by proninyaroslav** [comment]
Only with next release, sorry.

**Comment by zmni** [comment]
Oh..ok then. Thanks a lot.
________________________________
